json/UIText.txt
Added more translations, mostly centered on the quick search.
=> Added more translations

json/UIText.txt
Shop is about 80% done, still a bit more strings to be done.
Device ID transfer dialog translated, mostly.
Weapon Stats (long press) translated.
=> Added Shop translations

json/UIText.txt
Added more translations to I think the character creator and movement tutorials (still not done)
=> Corrected some stuff

json/UIText.txt
I don't know if the tutorial is finished, but with a linked character, it's done.
Can't say about es only characters.
=> Tutorial feels finished.

json/UIText.txt
Confirmed that the tutorials are translated.
Sega still has old tutorial for reasons unknown (probably laziness)
=> More menu translations etc

json/UIText.txt
Still a WIP, but will get there eventually.
=> Found more untranslated tutorial dialog =/

json/StoryEventText.txt
=> added the names for seraphy and jeane

json/UIText.txt
old tutorial is actually commented out
Old tutorial uses tu_ prefix
new uses tutorial_battle_ntu_
=> Updated the tutorial strings

json/UIText.txt
Also translated tutorial dialog for MyShop.
=> Character Creator menus added

json/InforTextActorMagTrigger.txt
=> Fixed a parsing error

json/UIText.txt
=> More menu stuff

json/UIText.txt
(percentages are estimate, but I feel like I'm almost there)
=> 70% done :D

json/UIText.txt
Just need the ARKS quest dialog (old story stuff) and we're good on this.
=> Tutorials are done.

json/UIText.txt
=> Ok this time, I'm pretty sure tutorials are done.

json/InforTextItemWeaponCompoundbow.txt
Just needs more descriptions and the name for the candy bow double drops.
=> Added 99.9% of the bow names

json/InforTextItemWeaponKatana.txt, json/InforTextItemWeaponKnuckle.txt
Knuckles and Katana names done.
=> Needs weapon descriptions

json/UIText.txt
Fixed various typos and other spelling mistakes.
=> Fixed typos

json/UIText.txt
Pet menu is translated!
Credits to Ricardo from Bumped for helping me with some parts of the pet menu.
=> Translated Pet menu and Storage

json/InforTextItemPetCandyStick.txt
Slight change for consistency with established affix translations
=> Completed edit

json/InforTextItemBaseWearFemale.txt, json/InforTextItemBaseWearMale.txt, json/InforTextItemInnerWearFemale.txt, json/InforTextItemInnerWearMale.txt, json/InforTextItemOuterFemale.txt, json/InforTextItemOuterMale.txt
=> Added TL's to Layered Clothing

json/InforTextItemStackGatCMatCereal.txt, json/InforTextItemStackGatCMatFruit.txt, json/InforTextItemStackGatCMatJewel.txt, json/InforTextItemStackGatCMatMineral.txt, json/InforTextItemStackGatCMatOther.txt, json/InforTextItemStackGatCMatVegetable.txt, json/InforTextItemStackGatFMatCrustacean.txt, json/InforTextItemStackGatFMatFish.txt, json/InforTextItemStackGatFMatOther.txt, json/InforTextItemStackGatFMatShellfish.txt, json/InforTextItemStackGatOMatMeat.txt
Food and Minerals Translated
-Skipped the flavor text however on all of them.
=> Food and Minerals Translated

json/InforTextItemStackBoost.txt, json/InforTextItemStackRoomgoods.txt
Translated some boost related items.
=> Added Newer Boost Tickets

json/InforTextItemStackBoost.txt
Jelly Drinks are apparently a thing in japan.
=> Jelly Drinks

json/InforTextItemAddonBack.txt
Reverts PolCPP/PSO2es-Translation#110
=> Revert "Update InforTextItemAddonBack.txt"

json/InforTextItemBaseWearFemale.txt, json/InforTextItemBaseWearMale.txt, json/InforTextItemCostumeFemale.txt, json/InforTextItemCostumeMale.txt, json/InforTextItemInnerWearFemale.txt, json/InforTextItemInnerWearMale.txt, json/InforTextItemOuterFemale.txt, json/InforTextItemOuterMale.txt
Reverts PolCPP/PSO2es-Translation#112
=> Revert "Translated Costumes and Layered Wear"

json/InforTextItemAddonBack.txt
Lines 292, 901, and 908 fixed.
=> Fixing invalid JSON

.travis.yml, checkjson.py, json/SideStoryEventText.txt
Here is a travis config (owner need to link travis buildbot to repos on own)
a Python the buildbot will run to check PRs
and a fix for SideStoryEventText.txt
=> Let use travis to check JSONs

checkjson.py
=> Clean Error output

json/InforTextItemStackLobbyAction.txt
=> Revert "Update InforTextItemStackLobbyAction.txt"

json/InforTextItemBaseWearFemale.txt, json/InforTextItemBaseWearMale.txt, json/InforTextItemCostumeFemale.txt, json/InforTextItemCostumeMale.txt, json/InforTextItemInnerWearFemale.txt, json/InforTextItemInnerWearMale.txt, json/InforTextItemOuterFemale.txt, json/InforTextItemOuterMale.txt, json/InforTextItemStackHairstyle.txt
Future Proofing so we don't have to care
=> Future Proof Costume/Layered Wear+Hairs

json/InforTextItemQuestTrigger.txt
Reverts PolCPP/PSO2es-Translation#168
=> Revert "Quest Trigger"

json/InforTextItemStackItemBag.txt
Reverts PolCPP/PSO2es-Translation#197
=> Revert "json fixed"

json/InforTextItemStackItemBag.txt, json/InforTextItemStackMusic.txt, json/InforTextItemStackPaidPass.txt, json/InforTextItemStackPaidTicket.txt, json/InforTextItemStackVoice.txt, json/InforTextItemWeaponRod.txt, json/InforTextItemWeaponTwinMachineGun.txt
Reverts PolCPP/PSO2es-Translation#196
=> Revert "Adding some fresh TL's first time in a long time"

json/Item_Stack_GatBoost.txt, json/Item_Weapon_AssaultRifle.txt, json/Item_Weapon_Compoundbow.txt, json/Item_Weapon_DoubleSaber.txt, json/Item_Weapon_DualBlade.txt, json/Item_Weapon_GunSlash.txt, json/Item_Weapon_JetBoots.txt, json/Item_Weapon_Katana.txt, json/Item_Weapon_Knuckle.txt, json/Item_Weapon_Launcher.txt, json/Item_Weapon_Partizan.txt, json/Item_Weapon_Rod.txt, json/Item_Weapon_Sword.txt, json/Item_Weapon_Tact.txt, json/Item_Weapon_Talis.txt, json/Item_Weapon_TwinDagger.txt, json/Item_Weapon_TwinMachineGun.txt, json/Item_Weapon_Wand.txt, json/Item_Weapon_WiredLance.txt
Thanks to Tey for description texts
=> Flavor text update

json/Explain_Element_Booster.txt, json/Explain_Element_UserSkill.txt, json/Explain_Potential.txt, json/Item_Stack_GatBoost.txt, json/Item_Stack_PaidPass.txt, json/Item_Weapon_AssaultRifle.txt, json/Item_Weapon_Compoundbow.txt, json/Item_Weapon_DualBlade.txt, json/Item_Weapon_GunSlash.txt, json/Item_Weapon_JetBoots.txt, json/Item_Weapon_Katana.txt, json/Item_Weapon_Knuckle.txt, json/Item_Weapon_Launcher.txt, json/Item_Weapon_Partizan.txt, json/Item_Weapon_Rod.txt, json/Item_Weapon_Sword.txt, json/Item_Weapon_Tact.txt, json/Item_Weapon_Talis.txt, json/Item_Weapon_TwinDagger.txt, json/Item_Weapon_TwinMachineGun.txt, json/Item_Weapon_Wand.txt, json/Item_Weapon_WiredLance.txt
=> flavor text translated and an entire weapon series renamed

json/Explain_Potential.txt, json/Explain_SkillRing.txt, json/Item_Costume_Female.txt, json/Item_Costume_Male.txt, json/Item_RingL.txt, json/Item_Stack_BodyPaint.txt, json/Item_Stack_Orderitem.txt, json/Item_Weapon_AssaultRifle.txt, json/SideStoryEvent_Text.txt, json/StoryEvent_Text.txt, json/StoryEvent_Title.txt, json/UI_Text.txt
also spoiler shit, don't peak in here yo
=> updating patch to conform with en patch

json/ChipExplain_SupportExplain.txt
hopefully they pass in one check D:
=> Finished translating support chips!

json/Name_Chip_ExtraName.txt, json/Name_Chip_SPArksName.txt, json/UI_Weaponoid_Name.txt, json/UI_Weaponoid_SideStoryOpen.txt
- Weaponoid Side Story unlock texts had some few strings translated.
- the current chips should be translated now
- the weaponoid list should be up to date now
=> Translated strings

json/Season1_Title.txt
Just a few things that need to be sorted...well, one:
-Vast sandbox? Shouldn't it be Vast Desert?
=> Season 1 Translation Work

json/Item_Disk_PAAssaultRifle.txt, json/Item_Disk_PACompoundbow.txt, json/Item_Disk_PADoubleSaber.txt, json/Item_Disk_PADualBlade.txt, json/Item_Disk_PAGunSlash.txt, json/Item_Disk_PAJetBoots.txt, json/Item_Disk_PAKatana.txt, json/Item_Disk_PAKnuckle.txt, json/Item_Disk_PALauncher.txt, json/Item_Disk_PAPartizan.txt, json/Item_Disk_PASword.txt, json/Item_Disk_PATwinDagger.txt, json/Item_Disk_PATwinMachineGun.txt, json/Item_Disk_PAWiredLance.txt
Adding new PA descriptions from the EN patch.
=> PA Disk Descriptions

json/Item_Weapon_AssaultRifle.txt, json/Item_Weapon_Launcher.txt, json/Item_Weapon_Sword.txt
Loads of launchers, evleda-family rifles and evleda-family swords
=> A load of weapon descriptions

json/Item_Disk_PACompoundbow.txt, json/Item_Disk_PADoubleSaber.txt, json/Item_Disk_PADualBlade.txt, json/Item_Disk_PASword.txt
somehow these ones got reverted last week
=> Refix PA disks

json/Item_Addon_Back.txt
Had this correct the first time, then doubted it
=> Don't second guess yourselves

json/Item_AvatarWPN_Katana.txt
Yukigaras needs to match the spelling of Yamigarasu since they're related.
=> Yuki and Yamigarasu matching

json/Item_Stack_Accessory.txt, json/Item_Stack_Hairstyle.txt, json/Item_Stack_ItemBag.txt
plus a couple corrections to stuff I got wrong or jumped the gun a bit on
=> Brave Cavalier G sets

_py/dupcheck.py, json/Items_Leftovers.txt
```
SP: Explain_Actor_MagAuto:Type2_3 '打撃/ブロー' wants the mapping of i's-atk / blow' but already got i'打撃デバイス／ブロー'
SP: Explain_Actor_MagAuto:Type3_3 '射撃/氷通常弾' wants the mapping of i'r-atk / ice bullet' but already got i'射撃デバイス／氷通常弾'
SP: Explain_Actor_MagAuto:Type3_4 '射撃/雷通常弾' wants the mapping of i'r-atk / lightning bullet' but already got i'射撃デバイス／雷通常弾'
SP: Explain_Actor_MagAuto:Type3_6 '射撃/闇通常弾' wants the mapping of i'r-atk / dark bullet' but already got i'射撃デバイス／闇通常弾'
SP: Explain_Actor_MagAuto:Type3_7 '射撃/光通常弾' wants the mapping of i'r-atk / light bullet' but already got i'射撃デバイス／光通常弾'
SP: Explain_Actor_MagAuto:Type3_17 '射撃/氷炸裂弾' wants the mapping of i'r-atk / exploding ice bullet' but already got i'射撃デバイス／氷炸裂弾'
SP: Explain_Actor_MagAuto:Type3_19 '射撃/風炸裂弾' wants the mapping of i'r-atk / …
```
=> Spacemapping script

json/Item_Stack_Orderitem.txt, json/Name_Quest_AreaName.txt, json/Name_Quest_PlaceName.txt, json/Name_Quest_QuestName.txt, json/SeraphyRoom_SeraphyNote.txt, json/SideStoryEvent_Title.txt, json/UI_Text.txt
Also some UI text and a couple other misc things.
=> Mostly quest names

json/Season2_Text.txt
@SynthSy @DabirSA 
Here's the Japanese -> English translation I was working on for the final chapter of Season 2.
I split sentences based mostly on the 23-24 characters per line limit, but you guys have more expertise with how it looks in-game so the break points might need to be adjusted.
I'm also missing some context when it comes to character personality / vocabulary in the existing English translations, so if something sounds odd coming from X character, please let me know and I'll be glad to adjust it.
=> Season 2 (Chapter 5)

json/ChipExplain_SupportExplain.txt, json/Item_AvatarWPN_Katana.txt, json/Item_BaseWear_Female.txt, json/Item_BaseWear_Male.txt, json/Item_Costume_Male.txt, json/Item_InnerWear_Female.txt, json/Item_InnerWear_Male.txt, json/Item_Outer_Female.txt, json/Item_Outer_Male.txt, json/Item_Parts_ArmFemale.txt, json/Item_Parts_BodyFemale.txt, json/Item_Parts_BodyMale.txt, json/Item_Parts_LegFemale.txt, json/Item_Stack_Accessory.txt, json/Item_Stack_BodyPaint.txt, json/Item_Stack_Hairstyle.txt, json/Item_Stack_ItemBag.txt, json/Item_Stack_Roomgoods.txt, json/Item_Stack_Voice.txt, json/UI_Text.txt
Typos, line breaks, incorrect colours in names, Goro Majima's name and more, mostly identified thanks to my automated item set tool
=> Corrections, mostly to item sets

json/Arles_Text.txt, json/Arles_Title.txt, json/ChipExplain_ActiveExplain.txt, json/Explain_Element_Booster.txt, json/Explain_Element_Special.txt, json/Item_Stack_PaidPass.txt, json/Leisure_PhotonDice_SpeakText.txt, json/Name_Quest_QuestName.txt, json/UI_Text.txt
- Completes the Story of Ares part 1 dialogue with help from Snack
- Updates stat-boosting affixes
- Translates Photon Dice dialogue for a number of characters and corrects it for a couple of others
- Various tweaks and corrections
=> Ares quest, dice lines, affixes

json/UI_Text.txt
Finished some story dialog bits for the Classic Season.
=> Some bits of the classic season translated

json/Season3_Text.txt, json/UI_Weaponoid_BallonName.txt
Making this its own PR so that future side story translation PRs are easier to deal with.
=> Side story speakers' names

json/ChipExplain_ActiveExplain.txt, json/ChipExplain_SupportExplain.txt, json/Item_Stack_Orderitem.txt, json/Name_Chip_ActiveName.txt, json/Name_Chip_SPArksName.txt, json/Name_Chip_SupportName.txt, json/Side_Title.txt, json/UI_Text.txt, json/UI_Weaponoid_BondsEffect.txt, json/UI_Weaponoid_ReleaseAbility.txt
- Retranslated PAs to match PC version where appropriate
- Translates a load of ability names
- Translates untranslated gaiden effects
- various fixes
=> Chips, abilities, UI

json/Illustrator.txt, json/Item_Weapon_Launcher.txt, json/Item_Weapon_Rod.txt
- Translated Seiyuus
- Corrected weapon names
=> Merge in changes

json/Item_Weapon_TwinDagger.txt
Obesity is a public health and policy problem.
=> Change Obessxion to Obsessxion

json/Item_Weapon_AssaultRifle.txt
To be consistent with Atlas and Atlas Ex.
=> Rename Val Rache to Val Drache

json/Item_Stack_Orderitem.txt, json/Item_Stack_Tool.txt
This reverts commit 84a3cf0c251e18935819d0a113f482f29ec2cc07.
=> Revert "item updates"

json/Explain_Potential.txt, json/Item_Stack_Accessory.txt, json/Name_Chip_SupportName.txt, json/Season3_Text.txt
Matching potential descriptions to what they are in the PC version (or at least what they are in my PR there).
=> Nyau hood, ability name, personalities and potentials

json/Item_AvatarWPN_Katana.txt
=> Grim Assassin

json/ChipExplain_SupportExplain.txt, json/Item_Stack_PaidPass.txt, json/Item_Weapon_AssaultRifle.txt, json/Item_Weapon_Compoundbow.txt, json/Item_Weapon_DoubleSaber.txt, json/Item_Weapon_GunSlash.txt, json/Item_Weapon_JetBoots.txt, json/Item_Weapon_Katana.txt, json/Item_Weapon_Knuckle.txt, json/Item_Weapon_Launcher.txt, json/Item_Weapon_Partizan.txt, json/Item_Weapon_Rod.txt, json/Item_Weapon_Sword.txt, json/Item_Weapon_Talis.txt, json/Item_Weapon_TwinDagger.txt, json/Item_Weapon_TwinMachineGun.txt, json/Item_Weapon_Wand.txt, json/Item_Weapon_WiredLance.txt, json/Name_Chip_SPArksName.txt, json/Name_Chip_SupportName.txt
+ some ability names and a chip description fix
=> Grammar fixes on twin weapon names and union descriptions

json/ChipExplain_SupportExplain.txt, json/Item_Stack_Music.txt, json/Name_Chip_SPArksName.txt, json/Name_Quest_AreaName.txt, json/Name_Quest_QuestName.txt, json/Side_Title.txt, json/UI_Text.txt, json/UI_Weaponoid_SideStoryOpen.txt
Also speakers' names for the newest gaidens.
=> Rose Flotz + start of Dragon Slayer gaidens

json/Item_QuestTrigger.txt, json/Item_Weapon_DualBlade.txt
- Fixes the Trigger names for Specter of Tragedy and Destruction
- Fixes novel dual blade name
=> Few item name fixes

json/Item_QuestTrigger.txt
This reverts commit 1ede81d20f3bc1ad19fc665d051f803de15b3779.
=> Revert "Woopsies"

json/Item_Stack_Tool.txt
- About the Gold & Silver medals. The actual term they use is closer to "a proof of accomplishment" You can change this later if someone complains about it.
=> Some item descriptions

json/Item_Stack_Accessory.txt, json/Item_Stack_DeviceHT.txt, json/Name_Actor_MagName.txt, json/Special_Text.txt, json/Special_Title.txt
=> Operation: Catch Santa

json/Item_Stack_PaidPass.txt
Just four after much long winded complaints
=> SSA name changes

json/Item_Stack_DeviceFD.txt, json/Item_Stack_DeviceHT.txt, json/Item_Stack_DeviceSAA.txt, json/Item_Stack_DeviceTA.txt
"Item Blue / Item Purple" -> "Item Blue/Item Purple"
=> Standardized use of slashes in item names.
